kind: Pod
apiVersion: v1
metadata:
  name: micro-pod
  labels:
    name: micro-pod
    app: micro-pod
spec:
  containers:
  - name: micro-pod
    image: 016973021151.dkr.ecr.us-west-2.amazonaws.com/dkrasimir/micro:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 300
    readinessProbe:
      httpGet:
        path: /micro-sample/rs/monitoring/ping
        port: 8080
      initialDelaySeconds: 300
    resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 800m
            memory: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: micro-pod
  labels: 
    app: micro-pod
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/exposeUrl: http://micro-pod.techtalk-int.tech-talk-ntt.com
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
spec:
  selector:
    app: micro-pod
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micro-pod
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: micro-pod.techtalk-int.tech-talk-ntt.com
    http:
      paths:
      - backend:
          serviceName: micro-pod
          servicePort: 80
